### ISSUE TITLE
Feature requests - link to node

### ISSUE THREAD

**Issue by Hatead** [retejs/comment-plugin#1]
If user press ctrl+С and one node is selected - hard link comment to node and drag comment with node, when node dragging.

**Comment by Ni55aN** [comment]
I think that the overlap will better represent the link. What do you think?

**Comment by Hatead1** [comment]
Возможно, так будет проще понять друг-друга: под hard link я подразумеваю привязку, логическую, коммента к ноде, а не физическую, как перекрытие. Созданный на выделенной ноде коммент, сам по себе всегда независимый и свободно передвигаемый, "привязывается" к ноде и при перемещении ноды тоже двигается, где бы он не находился. Проблема в том, что при использовании комментов получается двойная работа, если надо реорганизовать уже оформленную модель.

**Comment by Hatead1** [comment]
Т.е. если убрать перекрытие, сдвинув коммент, он "отвяжется"? Вполне нормальное решение.
Я уже проверил, не работает :) Но всё равно спасибо, это не горит.

**Comment by Ni55aN** [comment]
Новая фича: комментарии-фреймы https://rete.readthedocs.io/en/latest/Plugins/#comment
