### ISSUE TITLE
Draggable is moving after update the name

### ISSUE THREAD

**Issue by parox** [retejs/comment-plugin#20]
### Description
After edit a comment name the draggable component start to move according with mouse position.

### Steps to Reproduce
 - right click in a comment
 - change a value in the prompt
 - hit ok
 - move the mouse

### Expected Result
 The comment stay in the same position

### Current Result
 The comment starts to move according to the mouse

**Comment by parox** [comment]
I have also created a PR for this issue. Have a look
Hope it's of any help

https://github.com/retejs/comment-plugin/pull/19

**Comment by Ni55aN** [comment]
[v0.6.2](https://www.npmjs.com/package/rete-comment-plugin/v/0.6.2)

**Comment by parox** [comment]
Closing.
