### ISSUE TITLE
Add comments programmatically

### ISSUE THREAD

**Issue by Armaldio** [retejs/comment-plugin#4]
It could be great to be able to add comments programmatically instead of the shortcuts (e.g. from the context menu)

We could have something like

```js
editor.addInlineComment(text, position);
editor.addFrameComment(...);
etc..
```

**Comment by Ni55aN** [comment]
[v0.5.0](https://www.npmjs.com/package/rete-comment-plugin/v/0.5.0)

```js
editor.trigger('addcomment', ({ type: 'frame', nodes }))
editor.trigger('addcomment', ({ type: 'inline', position }))
```
