### ISSUE TITLE
Using it with Electron

### ISSUE THREAD

**Issue by DasDarki** [retejs/comment-plugin#6]
Hey,
I am trying to use this with Electron but I am stucking. Problem: The window.prompt is not implemented in Electron because of Thread Freezing. 
Would it possible to port this plugin for electron with an async renaming? Or is there another way?
Would be nice, if it is possible :)

**Comment by Ni55aN** [comment]
Yes, `window.prompt` could be replaced by optional modal window. I going to implement it soon, or you can replace [this](I going to implement it soon) by some parameter in [this function](https://github.com/retejs/comment-plugin/blob/c0a4416a14f9e1556e959912579009d767d66d7d/src/index.js#L8). It can be passed to CommentManager

**Comment by Ni55aN** [comment]
v0.6.0

```js
editor.use(CommentPlugin, { disableBuiltInEdit: true });

editor.on('editcomment', async (comment) => {
    comment.text = await openEditModal(comment.text);
    comment.update();
});
```

openEditModal should be async and return new value
