### ISSUE TITLE
When the parent comment move, the child comment doesn't move

### ISSUE THREAD

**Issue by lazzy07** [retejs/comment-plugin#9]
When creating a comment inside another comment, the child comment doesn't move with the parent comment.
As an example,
![unnamed](https://user-images.githubusercontent.com/34630697/63217433-27cac000-c164-11e9-9494-91e5b3f34214.jpg)
When "New Comment" move "undefined" does not move with it, which is not the expected result.

**Comment by mahsadarabi66** [comment]
good :) [دانلود آهنگ](https://naslemusic.com)
